# Generated by extendr: Do not edit by hand

# nolint start

#' @docType package
#' @usage NULL
#' @useDynLib masbayes, .registration = TRUE
NULL

#' Run BayesR MCMC
#' @export
run_bayesr_mcmc <- function(w, y, wtw_diag, wty, pi_vec, sigma2_vec, sigma2_e_init, prior_params, mcmc_params) {
    .Call(wrap__run_bayesr_mcmc, w, y, wtw_diag, wty, pi_vec, sigma2_vec, sigma2_e_init, prior_params, mcmc_params)
}

#' Run BayesA MCMC
#' @export
run_bayesa_mcmc <- function(w, y, wtw_diag, wty, nu, s_squared, sigma2_e_init, prior_params, mcmc_params) {
    .Call(wrap__run_bayesa_mcmc, w, y, wtw_diag, wty, nu, s_squared, sigma2_e_init, prior_params, mcmc_params)
}

# nolint end